### ISSUE TITLE
Help using Helder's RetroPSU with the shutdown circuit

### ISSUE THREAD

**Issue by DoomyDoomer** [geaz/simplyRetro-Z5#14] opened 2020-07-29 16:07 UTC
This isn't really an issue but more of a help request. I'm trying to apply your shutdown circuit to Helder's RetroPSU, which is similar to Adafruits PowerBoost 1000c. It has an EN pin that functions just like the PowerBoost. The problem I'm running into is once the "power" button is pressed, the system halts at "reboot: System halted", meaning it's ready to be rebooted/shutdown but the circuit doesn't seem to send the EN pin to ground to shut down the boost. If I short EN to GND manually, it shuts down. I've triple checked the circuit and I've wired it correctly. The Pi is running on RetroPie with SPI on and your other config.txt values. I manually installed WiringPi as well since it's a dependency on the retropower application. Any help you can offer is appreciated.

**Comment by geaz** [comment] 2020-07-29 16:22
May I ask which distribution you are using? Because it sounds like the GPIO 7 pin is not set to LOW on system shutdown. The powering circuit requires the "dtoverlay" _gpio-poweroff_ which not every distribution has included.

**Comment by DoomyDoomer** [comment] 2020-07-29 16:26
I'm running RetroPie 4.14.98-v7+

**Comment by geaz** [comment] 2020-07-29 16:52
As far as I know it should be included. 
Can you check the voltage of GPIO 7 on a running system and a halted one (not powered off)?

**Comment by DoomyDoomer** [comment] 2020-07-29 17:13
3.3v when the system is running and like 6mv when halted, so it appears to be running correctly. I'm stumped.

**Comment by geaz** [comment] 2020-07-29 17:42
Are you sure the ground <-> enable pin connection is correct? Correct resistors, too? If the GPIO 7 is running correctly and your system keeps running on the initial button press, it seems like the ground <-> enable pin is somehow not working as it should.

**Comment by DoomyDoomer** [comment] 2020-07-29 20:19
I think you're right. I'm not sure why I'm having this issue just by looking at the circuit I've built but I'll continue to test. I did bring up the issue to Helder, the maker of the RetroPSU and he put together OSH Park circuit of your Schematic: https://oshpark.com/shared_projects/AFSBND5u This might help people who don't want to mess with stripboard/perfboard :)

**Comment by geaz** [comment] 2020-07-29 20:52
Thats pretty cool, thanks for the link!
I hope you will find the "bug" :)

**Comment by DoomyDoomer** [comment] 2020-07-29 21:14
No problem! Like you, Helder is a huge help with these circuits. I do have one other quick question around the amount of Diodes on your circuit. Usually I see two diodes on circuits such as this. Is the the third diode to reduce the amount of voltage going through to Pin 19?

**Comment by geaz** [comment] 2020-07-30 05:19
Exactly, the third diode drops (resulting in two diodes in series) the voltage to a usable one for pin 19.

**Comment by DoomyDoomer** [comment] 2020-07-30 16:02
After looking over everything several times and making sure all connections are correct to the best of my ability, I'm still not able to power down the boost with the long press of the button. At this point, I wonder if you could take a look at my circuit and let me know if what I've done is correct or not. It's such a simple circuit so I'm struggling to find what is the problem.  I appreciate all of your help so far.

[My Circuit from the front](https://cdn.humblebazooka.com/wp-content/uploads/2020/07/IMG_20200730_103304-scaled.jpg)
_Top Yellow wire is EN, Bottom is CPIO 7, Green is GPIO 19_

[Circuit from the back](https://cdn.humblebazooka.com/wp-content/uploads/2020/07/IMG_20200730_103256-scaled.jpg)

[Circuit back diagram to help explain all the mess](https://cdn.humblebazooka.com/wp-content/uploads/2020/07/simplyRetroZ5_pwr_circ.jpg)

[RetroPSU showing BAT+, EN, 5v PWR, and GND wired to the circuit](https://cdn.humblebazooka.com/wp-content/uploads/2020/07/IMG_20200730_103323-scaled.jpg)

[Pi connections](https://cdn.humblebazooka.com/wp-content/uploads/2020/07/IMG_20200730_103315-scaled.jpg)
_SDA and SDL pins are for a separate battery monitoring script. Pin 7 wire goes to pwr circuit_

My boot config.txt
[config.txt](https://github.com/geaz/simplyRetro-Z5/files/5002371/config.txt)

[My start script for retropower](https://cdn.humblebazooka.com/wp-content/uploads/2020/07/Screenshot-2020-07-30-11.30.45.png)

The "retropower" app is in /usr/bin/ with the proper permissions and does start at boot. It is started at boot by an init.d script called "startRetropower" shown above.

Please let me know if you need anymore information and I appreciate all your help.

**Comment by geaz** [comment] 2020-07-30 17:08
As far as I can see it looks fine. Two questions:
1. By "not able to power down the boost with the long press" you mean, the system gets halted (shutdown is initiated by the retroPower tool), but the power does not get disabled, right?
2. Did you measure with a multimeter, if your enable pin and the GPIO 7 has a working connection? (Just in case: measure the resistance - it should be ~0 Ohm - otherwise the connection is not working).

**Comment by DoomyDoomer** [comment] 2020-07-30 17:20
1. Exactly. It shutsdown the pi but halts at the terminal waiting to be physically turned off.
2. Do you mean I should measure by taking one lead and putting it on my EN and the other on Pin 7 when the system is in "halt" state? If so, when I do this I don't see any reading on my multimeter.

**Comment by geaz** [comment] 2020-07-30 17:28
1. Perfect, the retroPower application is doing it's work correctly. At least something :)
2. You are able to measure it in a powered off state, too. And yes, one lead at the enable pin and the other one on GPIO 7. If you don't get any measures, it means, that the connection between these two points is not working.

You now could use the same method to measure each point in between to get the points where the connection is "lost" (maybe a not working soldering point?).

**Comment by geaz** [comment] 2020-07-30 17:36
One more thing: make sure to use the leads in the correct direction because of the diodes....

**Comment by DoomyDoomer** [comment] 2020-07-30 17:41
Ok this is weird. I used a different multimeter for sanity check. When I have my PSU plugged in (load share) I get 10k ohm between EN and pin 7. If the USB power is removed from the PSU, it's reading as 8.89 and steadily dropping. This is during the halt state. It seems like it's holding a resistance but I could be saying that wrong.

**Comment by geaz** [comment] 2020-07-30 17:48
Could you please also measure the ground <-> enable pin connection, too?

**Comment by DoomyDoomer** [comment] 2020-07-30 17:52
When I test continuity the system reboots unless I hold the leads to the pins, so connection is there ha! 0 ohm when testing resistances.

**Comment by geaz** [comment] 2020-07-30 18:16
So it is "working", if you test with the leads? Did you measure it also in a powered off state?

**Comment by DoomyDoomer** [comment] 2020-07-30 18:22
Right, because touching one lead to EN and another to GND disables the PSU (just like the powerboost). I don't know how I can test resistance without causing it to power off completely, or is that what you're looking for me to try? Again, thanks for continuing to try to help me.

**Comment by geaz** [comment] 2020-07-30 18:22
And one more (sorry): also check GPIO 7 <-> ground

**Comment by geaz** [comment] 2020-07-30 18:41
To summarize what we tested and worked until now:
1. Connections between the following pins is working:
GND <-> EN
GND <-> GPIO 7
GPIO 7 <-> EN (otherwise powering on wouldn't work, if I think about it)
2. GPIO 7 is HIGH during a running system and LOW during a halted system

The only thing what could be wrong are the resistors now (if I am not totally wrong). According to the color codes the resistors are fine (2x 10k and 1x 100k). Just to make sure, that they are working, did you test them with the multimeter? If the 100k resistor ist broken the circuit will not work (just one of many possibilities).

**Comment by DoomyDoomer** [comment] 2020-07-30 19:02
I've tested resistance between GND and EN, all in the k ohms. I swapped out the 100k resistor and tested it's resistance when it was free and it was at 99.8k which I assume is in spec of 100k. I'm at a loss!

**Comment by DoomyDoomer** [comment] 2020-07-30 19:05
Here's another question - with this circuit in place, shouldn't the Pi stay powered OFF until a button press? Because as soon as I toggle battery on, the pi boots as if it's getting direct power. That seems wrong.

**Comment by geaz** [comment] 2020-07-30 19:09
What exactly do you mean with "toggle battery on"? the pi should stay off until the "power on" button (the switch in the circuit) gets pressed.

**Comment by DoomyDoomer** [comment] 2020-07-30 19:11
I have a simple toggle switch on the BAT+ line before the PSU so I can quickly disconnect the battery if needed. It's just a safety feature and shouldn't impact the circuit at all. Ok, that's what I thought. See when I "connect" the battery to the PSU, the pi powers on without a button press.

**Comment by geaz** [comment] 2020-07-30 19:14
That means that the EN Pin does not get pulled down to ground correctly. What causes the problem during shutdown, too. I can't tell you exactly what is wrong with this connection, but the PSU should be disabled, if EN is pulled down to ground correctly (like the power boost). I am 99% sure that this connection is the problem.

**Comment by DoomyDoomer** [comment] 2020-07-30 19:29
That makes sense. The EN wire on the circuit goes to the middle extension rail which takes it to the 100k resistor (pull-down?) to GND until the button is pressed which pulls EN from GDN. This should keep the EN pin and GND pin connected and disable the PSU's 5v output. The EN wire through to the 100k resistor all tests fine on the continuity. This is very confusing. Did you have time to look over Helder's OSH Park circuit? if it looks ok to you, I think I might buy a few of those to rule out my circuit all together even though I can't find a single fault with it. I don't know what else to try at this point since all components are working correctly separately.

**Comment by geaz** [comment] 2020-07-30 19:38
I looked on your pictures again and I have a question: Did you connect the circuit to the "Bat+" of the Retro PSU? If so, please connect it to the second "5v rail". This could be the problem.

**Comment by DoomyDoomer** [comment] 2020-07-30 19:46
That's correct because the RetroPSU doesn't have a pass through BAT pin like the PowerBoost. I just moved "PowerBoost BAT" wire to the 5v output of the RetroPSU. No change unfortunately. 
![IMG_20200730_154258](https://user-images.githubusercontent.com/57010233/88967466-dedc2080-d27b-11ea-92ed-dcd23f0a6ccb.jpg)
![IMG_20200730_154316](https://user-images.githubusercontent.com/57010233/88967467-dedc2080-d27b-11ea-954c-47f8198d2eb4.jpg)

**Comment by geaz** [comment] 2020-07-30 19:57
Hmm, was worth a try :)
At this point I am just guessing...but could you try to disconnect GPIO 7 and test, if the power stays off as soon as you connect the battery?

**Comment by DoomyDoomer** [comment] 2020-07-30 19:59
Powers right on LOL... So I'm talking with the creator of the PSU and he's telling me his EN is pulled high with a 10k resistor. I'm at this point beyond my knowledge level as to wether or not makes any difference to this circuit but I figured the more info I can provide the better.

**Comment by geaz** [comment] 2020-07-30 20:09
Ah I see. Switch the 100k with something >1k and <10k. Keep GPIO 7 disconnected and test, if it still powers on.

**Comment by DoomyDoomer** [comment] 2020-07-30 20:19
Ok swapped in a 5.6k. GPIO pin 7 off, powers up and stays on. Connected pin 7 again and powered off with the switch, same outcome.

**Comment by geaz** [comment] 2020-07-30 20:23
Did it automatically switched on with GPIO7 disconnected? Or did you have to press the switch?

**Comment by DoomyDoomer** [comment] 2020-07-30 20:23
Automatically switched on :(

**Comment by geaz** [comment] 2020-07-30 20:30
What the hell...I think we have to redesign the circuit a bit for the RetroPSU. It would not help you to order the OSHPark one. 

I think the resistor has to be <5.6k, but I can't tell you how small exactly (maybe try smaller one until it keeps powered off). But keep in mind, if you try other ones, you have to change the 10k one on GPIO7 with an even smaller resistor. The third one can stay the same.

**Comment by DoomyDoomer** [comment] 2020-07-30 20:34
My reaction exactly! haha I’m going to try smaller ones and see where I land. How will I know if I need to change the GPIO 7 resistor? Luckily I have a ton of resistors at my disposal.

**Comment by geaz** [comment] 2020-07-30 20:53
Now that I think about it, the GPIO 7 resistor could maybe stay as it is. First try smaller resistors until the pi stays powered off with a connected battery. Then connect GPIO 7 and test, if it everything works as intended.

**Comment by geaz** [comment] 2020-07-30 22:13
One more thing you could test: Try to remove the resistor and add a bridge/jumper instead and check, if it stays off (just don't press the switch, otherwise you will short your PSU). Just want to make sure, that the connection is really working, because the more I think about it, the value of the resistor should be irrelevant....it is just there to prevent a short when the button is pressed. But I could be totally wrong - unfortunately I am a layman, too.

**Comment by DoomyDoomer** [comment] 2020-07-30 22:19
It does indeed stay off if I bridge the connections. That said, I finally have some results. I’ve used 2.2k, 2k, 1.5k, 1k. 2.2k, Pi comes right on. 2.0k stays off BUT I can’t power the Pi on now with pin 7. I’m not probably going to stack up some values < 1k and see if I can get it to power back up.

**Comment by DoomyDoomer** [comment] 2020-07-30 22:39
Well scratch that. 2k resistor keeps the pi down until a press of the tactile button. But get this, on long press shut down, the pi still stays halted and the PSU still remains live! Back to square one?

**Comment by geaz** [comment] 2020-07-30 22:39
I think we now got to the next problem :)
If you use the 2k resistor and connect and keep the switch pressed, does the pi turn on and as soon as you release the switch it turns off?

**Comment by geaz** [comment] 2020-07-30 22:43
Just for my understanding: with 2k the pi stays powered off and on button press it powers on correctly, but the shutdown does still not work?

**Comment by DoomyDoomer** [comment] 2020-07-30 22:46
Yes, exactly!

**Comment by geaz** [comment] 2020-07-30 22:52
Ok, at least the powering on works as it should now :)
I am again just guessing, but:
It sounds like we don't get the EN Pin pulled down enough with the 2k resistor and that the remaining voltage on the GPIO 7 in the halted state is enough to keep it HIGH. Maybe we can fix this with a higher resistor at the GPIO 7 pin? Maybe 100k instead of 10k?

**Comment by DoomyDoomer** [comment] 2020-07-30 23:03
That makes sense. 100k isn’t doing the trick but I’ll keep testing >. I almost thought it worked but it turned out I touched both ends of the resistor which powered down the Pi. Getting closer though.

**Comment by geaz** [comment] 2020-07-30 23:08
Maybe you could also try to get smaller than 2k on the EN pin <-> gnd resistor. To do a "harder" pull to ground.

**Comment by DoomyDoomer** [comment] 2020-07-30 23:16
Seems like nothing lower than 2k wants work and anything higher powers the Pi right on.

**Comment by geaz** [comment] 2020-07-31 04:28
With "Seems like nothing lower than 2k wants work" you mean the powering on works as intended, but the powering off not?

**Comment by DoomyDoomer** [comment] 2020-07-31 04:44
What I meant was, when I use a smaller than 2k resistor between EN and GND, the pi won't power on with a button press. 2k seemed to be the sweet spot.

**Comment by geaz** [comment] 2020-07-31 04:52
Ok, did you try anything >100k on the GPIO 7 together with the 2k?

**Comment by DoomyDoomer** [comment] 2020-07-31 05:00
Not yet but I plan to tomorrow. I feel like it's very close if I can just figure out the shutdown.

**Comment by geaz** [comment] 2020-07-31 05:03
Yeah, a working power on was a good step :)
Hoping that >100k is doing the trick for the power off now.

**Comment by DoomyDoomer** [comment] 2020-07-31 13:38
I've hit another issue it seems. I decided to charge the battery while trying out different resistors and realized that now as soon as the USB charger is attached, the Pi comes right on with the 2k resistor in place. It really seems like this circuit just isn't going to work for my PSU :( Too many variables.

**Comment by geaz** [comment] 2020-07-31 13:47
That's all really strange to be honest....and I am very sorry, that it does not work for you. But did you look into https://github.com/Helder1981/OneForAll it seems to be something like retroPower, but for the RetroPSU.

**Comment by DoomyDoomer** [comment] 2020-07-31 13:52
Very strange indeed but it's ok and you have nothing to be sorry about. I really appreciate you spending so much time with me trying to troubleshoot this. I actually have Helder's OneForAll installed and running. Funny enough, the gpio-shutdown pin 7 line in the boot config breaks support for the battery monitoring even though nothing is interfering with SDA and SDL, which it uses. Just another headache I can't solve at the moment.

**Comment by geaz** [comment] 2020-07-31 14:03
As far as I know SPI and I2C are disabled per default on raspian (Retropie is based on it don't know, if they are activating it). You have to activate it in the raspi-config in the "Interfacing" menu.

**Comment by DoomyDoomer** [comment] 2020-07-31 14:06
You are correct but I have activated those in the config.txt but his AllForOne installer does this automatically just in case. If I remove the gpio-shutdown overlay, the monitoring comes back to life. Just another wrinkle :)

**Comment by geaz** [comment] 2020-07-31 14:07
And you should delete retroPower, if you are using OneForAll. It interferes with SPI and I don't know, if this can be a problem for OneForAll.

**Comment by DoomyDoomer** [comment] 2020-07-31 14:10
Good call, I plan to remove it. OneForAll does not have safe shut down for a switch by default. It does however have a monitor that shuts down if the battery hits a certain voltage.

**Comment by geaz** [comment] 2020-07-31 14:15
I just saw in the readme the config option "SHUTDOWN_DETECT". Sounds like this is a safe shutdown by driving a GPIO low. Connect the switch between a GPIO which is pulled high per default (GPIO 7 for example :D) and ground. Insert the GPIO 7 into the config option and now, pressing the switch should shutdown the system. If I understand the readme correctly. But I think it won't disable the PSU?

**Comment by DoomyDoomer** [comment] 2020-07-31 14:19
Right, exactly. You still need a circuit to pull EN to GND to shutdown the PSU. I actually have another circuit I built before trying out yours which used a dual diode and duel mosfet, which triggers the shutdown but does not disable the PSU. I've been chasing the dream of a safe shut down for a long time but I just can't grasp it!

**Comment by geaz** [comment] 2020-07-31 14:26
One last question, did you test to completely disconnect the custom circuit, to test, if the PSU still does only stay powered off with a 2k resistor (want to make sure, that the circuit itself is interfering with this functionality)?

Because you told me, that anything higher would power it on directly, I think, that connecting the USB is pushing the voltage just enough to switch EN to HIGH. This indicates that we have to use a lower resistor.

**Comment by geaz** [comment] 2020-07-31 14:27
I am just refusing to give up now :D

**Comment by geaz** [comment] 2020-07-31 14:29
One more thing: I just created a Discord server (do you have a Discord account?). This is getting very chatty and it would be better to talk there. 

https://discord.gg/VFq68m

**Comment by DoomyDoomer** [comment] 2020-07-31 14:36
I was going to suggest the same thing. It looks like that invite is invalid.

**Comment by geaz** [comment] 2020-07-31 14:39
https://discord.gg/92Xk4aS

Hope this one works :)

**Comment by geaz** [comment] 2020-07-31 14:42
Closing this. Further discussion on Discord.

**Closed** 2020-07-31 14:42 UTC
